import { Dimensions, Platform, StyleSheet } from "react-native";
import { COLORS } from "@/constants";

const { width } = Dimensions.get("window");

export const DETAIL_IMAGE_WIDTH = width;
export const DETAIL_IMAGE_HEIGHT = 350;

export const propertyDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  backButton: {
    marginTop: 20,
    padding: 12,
    backgroundColor: COLORS.primary,
    borderRadius: 8,
  },
  backButtonText: {
    color: COLORS.white,
    fontWeight: "600",
  },
  imageContainer: {
    width: "100%",
    backgroundColor: COLORS.white,
  },
  image: {
    width,
    height: DETAIL_IMAGE_HEIGHT,
    resizeMode: "cover",
  },
  backFloating: {
    position: "absolute",
    top: Platform.OS === "ios" ? 60 : 40,
    left: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.blackTransparent50,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  imageBadge: {
    position: "absolute",
    bottom: 26,
    right: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: COLORS.blackTransparent60,
  },
  imageBadgeText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: "bold",
  },
  floatingActions: {
    position: "absolute",
    right: 8,
    top: 0,
    bottom: 0,
    justifyContent: "center",
    zIndex: 10,
    alignItems: "center",
  },
  actionsScrim: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: 84,
    zIndex: 9,
  },
  content: {
    paddingTop: Platform.OS === "ios" ? 50 : 30,
    paddingHorizontal: 20,
    paddingBottom: 20,
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginTop: -24,
  },
  headerInfo: {
    marginBottom: 16,
  },
  metaRowContent: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  idContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  copyIcon: {
    marginLeft: 4,
  },
  metaSeparator: {
    marginHorizontal: 8,
    color: COLORS.textSecondary,
    fontSize: 12,
  },
  metaText: {
    fontSize: 12,
    color: COLORS.textSecondary,
    fontWeight: "600",
  },
  tagRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  typeTag: {
    backgroundColor: COLORS.gradientBackground,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  typeTagText: {
    color: COLORS.primary,
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: COLORS.textPrimary,
    marginBottom: 8,
    lineHeight: 30,
  },
  priceContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  priceBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.textPrimary,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 8,
  },
  operationType: {
    color: COLORS.textTertiary,
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
  },
  price: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.white,
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
  },
  locationText: {
    fontSize: 15,
    color: COLORS.textSecondary,
    flex: 1,
    lineHeight: 20,
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.cardBorder,
    marginVertical: 24,
  },
  section: {
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.textPrimary,
    marginBottom: 16,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  statItem: {
    width: "48%",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.white,
    padding: 10,
    borderRadius: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
  },
  statIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.gradientBackground,
    justifyContent: "center",
    alignItems: "center",
  },
  statTextContainer: {
    flex: 1,
  },
  statValue: {
    fontSize: 14,
    fontWeight: "bold",
    color: COLORS.textPrimary,
  },
  statLabel: {
    fontSize: 10,
    color: COLORS.textSecondary,
    textTransform: "uppercase",
    fontWeight: "600",
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.background,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
  },
  chipText: {
    fontSize: 13,
    color: COLORS.textSecondary,
    fontWeight: "500",
  },
  amenitiesContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  amenityChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.primaryLight,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
  },
  amenityText: {
    color: COLORS.primaryDark,
    fontSize: 13,
    fontWeight: "500",
  },
  descriptionText: {
    fontSize: 15,
    color: COLORS.textSecondary,
    lineHeight: 26,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.textPrimary,
  },
  warningBox: {
    flexDirection: "row",
    padding: 16,
    backgroundColor: COLORS.warningLight,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.warning,
    gap: 12,
  },
  warningTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.warningDark,
    marginBottom: 4,
  },
  warningText: {
    fontSize: 14,
    color: COLORS.warning,
    lineHeight: 20,
    flex: 1,
  },
  commissionBox: {
    backgroundColor: COLORS.infoLight,
    borderWidth: 1,
    borderColor: COLORS.info,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  commissionTitle: {
    fontWeight: "bold",
    color: COLORS.infoDark,
    marginBottom: 8,
    fontSize: 14,
  },
  commissionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  commissionLabel: {
    fontSize: 13,
    color: COLORS.info,
  },
  commissionValue: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.infoDark,
    maxWidth: "60%",
    textAlign: "right",
  },
  profileSection: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
  },
  profileFoto: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 12,
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.textPrimary,
  },
  profileRole: {
    fontSize: 12,
    color: COLORS.textSecondary,
  },
  contactIconBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.white,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
  },
  mainContactBtn: {
    backgroundColor: COLORS.primary,
    padding: 18,
    borderRadius: 16,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 40,
  },
  mainContactBtnText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: "bold",
  },
});
