/**
 * Catálogo de ubicaciones de México (En cascada)
 * Estado → Ciudad → Municipio → Colonia
 */

export const ESTADOS_MEXICO = [
  "Aguascalientes",
  "Baja California",
  "Baja California Sur",
  "Campeche",
  "Chiapas",
  "Chihuahua",
  "Ciudad de México (CDMX)",
  "Coahuila de Zaragoza",
  "Colima",
  "Durango",
  "Estado de México",
  "Guanajuato",
  "Guerrero",
  "Hidalgo",
  "Jalisco",
  "Michoacán de Ocampo",
  "Morelos",
  "Nayarit",
  "Nuevo León",
  "Oaxaca",
  "Puebla",
  "Querétaro",
  "Quintana Roo",
  "San Luis Potosí",
  "Sinaloa",
  "Sonora",
  "Tabasco",
  "Tamaulipas",
  "Tlaxcala",
  "Veracruz de Ignacio de la Llave",
  "Yucatán",
  "Zacatecas",
] as const;

export type EstadoMexico = (typeof ESTADOS_MEXICO)[number];

// ============================================
// COORDENADAS: Estado
// ============================================

export const COORDENADAS_ESTADO: Record<string, { lat: number; lng: number }> =
  {
    Aguascalientes: { lat: 21.8853, lng: -102.2916 },
    "Baja California": { lat: 30.8406, lng: -115.2838 },
    "Baja California Sur": { lat: 24.1426, lng: -110.3128 },
    Campeche: { lat: 19.8301, lng: -90.5349 },
    Chiapas: { lat: 16.7569, lng: -93.1292 },
    Chihuahua: { lat: 28.6329, lng: -106.0691 },
    "Ciudad de México (CDMX)": { lat: 19.4326, lng: -99.1332 },
    "Coahuila de Zaragoza": { lat: 27.0587, lng: -101.7068 },
    Colima: { lat: 19.2452, lng: -103.7241 },
    Durango: { lat: 24.5593, lng: -104.6588 },
    "Estado de México": { lat: 19.285, lng: -99.5496 },
    Guanajuato: { lat: 21.019, lng: -101.2574 },
    Guerrero: { lat: 17.4392, lng: -99.5451 },
    Hidalgo: { lat: 20.0911, lng: -98.7624 },
    Jalisco: { lat: 20.6597, lng: -103.3496 },
    "Michoacán de Ocampo": { lat: 19.5665, lng: -101.7068 },
    Morelos: { lat: 18.6813, lng: -99.1013 },
    Nayarit: { lat: 21.7514, lng: -104.8455 },
    "Nuevo León": { lat: 25.5922, lng: -99.9962 },
    Oaxaca: { lat: 17.0732, lng: -96.7266 },
    Puebla: { lat: 19.0414, lng: -98.2063 },
    Querétaro: { lat: 20.5888, lng: -100.3899 },
    "Quintana Roo": { lat: 19.1817, lng: -88.4791 },
    "San Luis Potosí": { lat: 22.1565, lng: -100.9855 },
    Sinaloa: { lat: 25.1721, lng: -107.4795 },
    Sonora: { lat: 29.2972, lng: -110.3309 },
    Tabasco: { lat: 17.8409, lng: -92.6189 },
    Tamaulipas: { lat: 24.2669, lng: -98.8363 },
    Tlaxcala: { lat: 19.3139, lng: -98.2404 },
    "Veracruz de Ignacio de la Llave": { lat: 19.1738, lng: -96.1342 },
    Yucatán: { lat: 20.7099, lng: -89.0943 },
    Zacatecas: { lat: 22.7709, lng: -102.5832 },
  };

// ============================================
// ESTRUCTURA: Estado → Ciudades
// ============================================
export const CIUDADES_POR_ESTADO: Record<string, string[]> = {
  Aguascalientes: [
    "Aguascalientes",
    "Calvillo",
    "Jesús Maria",
    "Rincón de Romos",
    "Pabellón de Arteaga",
    "San Francisco de los Romo",
    "Asientos (Real de Asientos)",
    "San José de Gracia",
    "Cosío",
    "El Llano",
    "Tepezalá",
  ],
  "Baja California": [
    "Tijuana",
    "Mexicali",
    "Ensenada",
    "Rosarito",
    "Tecate",
    "San Quintín",
    "San Felipe",
    "La Rumorosa",
    "Michoacán de Ocampo",
  ],
  "Baja California Sur": [
    "La Paz",
    "Los Cabos",
    "Loreto",
    "San José del Cabo",
    "Ciudad Constitución",
    "Santa Rosalía",
    "Ciudad Insurgentes",
    "Cabo San Luca",
    "Todos Santos",
    "Heroica Mulegé",
    "Guerrero Negro",
    "Puerto San Carlos",
    "Puerto Adolfo López Mateos",
    "Los Barriles",
    "El Pescadero",
    "Villa Alberto A.",
    "El Centenario",
    "Melitón Albáñez D.",
    "Villa Morelos",
    "Bahía Asunción",
    "Miraflores",
    "San Ignacio",
    "Las Veredas",
    "Las Palmas",
    "San Francisco",
    "Ensenada Blanca",
    "San Felipe",
    "Puerto Agua Verde",
    "San Bernardo",
    "Puerto Chale",
    "Misión Lote 26",
    "Puerto Escondido",
    "El Santo Niño",
    "San Javier",
    "El Triunfo",
  ],
  Campeche: [
    "Alfredo V. Bonfil",
    "Balancán",
    "Bolonchén",
    "Bécal",
    "Calakmul",
    "Calkiní",
    "Campeche",
    "Candelaria",
    "Celestún",
    "Centla",
    "Champotón",
    "Chencoh",
    "Ciudad del Carmen",
    "Conhuas",
    "Emiliano Zapata",
    "Escárcega",
    "Flores",
    "Halachó",
    "Hecelchakán",
    "Hopelchén",
    "Isla Aguada",
    "Isla Arena",
    "Jonuta",
    "José María Morelos",
    "Lerma",
    "Malecón de Campeche",
    "Maxcanú",
    "Melchor de Mencos",
    "Mérida",
    "Noh-Yaxché",
    "Oxkutzcab",
    "Palizada",
    "Sabancuy",
    "San Andrés",
    "San Joaquín",
    "San José",
    "Santa Elena",
    "Santa Rosa",
    "Seybaplaya",
    "Siho Playa",
    "Tekax",
    "Tenabo",
    "Tikinmul",
    "Tixmucuy",
    "Uayamón",
    "Villa Madero",
    "Xpujil",
  ],
  Chiapas: [
    "Cintalapa de Figueroa",
    "San Cristóbal de las Casas",
    "Tuxtla Gutiérrez",
    "Palenque",
    "La Trinitaria",
    "Benemérito de las Américas",
    "Tzimol",
    "Ciudad Hidalgo",
    "Pueblo Nuevo Solistahuacán",
    "Chilón",
    "Teopisca",
    "Motozintla de Mendoza",
    "Villa Corzo",
    "Pijijiapan",
    "Comitán de Domínguez",
    "Tapachula",
    "Tonalá",
    "Copainalá",
    "Suchiapa",
    "Huixtla",
    "Ixtacomitán",
    "Acacoyagua",
    "Yajalón",
    "Tapilula",
    "Mapastepec",
    "Amatenango del Valle",
    "Berriozábal",
    "Ocotepec",
    "Ocozocoautla de Espinosa",
    "Simojovel de Allende",
    "Tuxtla Chico",
    "Ixtapa",
    "Las Margaritas",
    "Mazatán",
    "Escuintla",
    "Arriaga",
    "Las Rosas",
    "Jiquipilas",
    "Juárez",
    "La Libertad",
    "El Bosque",
    "Pichucalco",
    "Ochusjob",
    "Altamirano",
    "La Concordia",
    "Acapetahua",
    "San Fernando",
    "Jaltenango de la Paz",
    "Venustiano Carranza",
    "Raudales Malpaso",
    "Frontera Comalapa",
  ],
  Chihuahua: [
    "Ahumada B",
    "Aldama ",
    "Allende ",
    "Aquiles Serdán ",
    "Ascensión ",
    "Bachíniva ",
    "Balleza ",
    "Batopilas ",
    "Bocoyna ",
    "Buenaventura ",
    "Camargo ",
    "Carichí ",
    "Casas Grandes ",
    "Coronado ",
    "Coyame del Sotol ",
    "La Cruz ",
    "Cuauhtémoc ",
    "Cusihuiriachi ",
    "Chihuahua ",
    "Chínipas ",
    "Delicias ",
    "Dr. Belisario Domínguez ",
    "Galeana ",
    "Santa Isabel ",
    "Gómez Farías ",
    "Gran Morelos ",
    "Guachochi ",
    "Guadalupe y Calvo ",
    "Guazapares ",
    "Guerrero ",
    "Hidalgo del Parral ",
    "Huejotitán ",
    "Ignacio Zaragoza ",
    "Janos ",
    "Jiménez ",
    "Julimes ",
    "López ",
    "Madera ",
    "Maguarichi ",
    "Manuel Benavides ",
    "Matachí ",
    "Matamoros ",
    "Meoqui ",
    "Morelos ",
    "Mori",
    " Namiquipa",
    " Nonoava",
    " Nuevo Casas Grandes",
    " Ocampo",
    " Ojinaga",
    " Riva Palacio",
    " Rosales",
    " Rosario",
    " San Francisco de Borja",
    " San Francisco de Conchos",
    " San Francisco del Oro",
    " Santa Bárbara",
    " Satevó",
    " Saucillo",
    " Temósachic",
    " El Tule",
    " Urique",
    " Uruachi",
    " Valle de Zaragoza",
  ],
  "Ciudad de México (CDMX)": ["Ciudad de México"],
  "Coahuila de Zaragoza": [
    "Saltillo",
    "Torreón",
    "Monclova",
    "Piedras Negras",
    "Ciudad Acuña",
    "Ramos Arizpe",
    "Frontera",
    "Matamoros",
    "Sabinas",
    "San Pedro",
    "Ciudad Melchor Múzquiz",
    "Parras de la Fuente",
    "Francisco I. Madero",
    "Castaños",
    "Nava",
    "San Buenaventura",
    "Allende",
    "Arteaga",
    "Zaragoza",
    "Cuatro Ciénegas de Carranza",
    "General Cepeda",
    "Nadadores",
    "Viesca",
    "Morelos",
    "Lamadrid",
    "Abasolo",
    "Sacramento",
    "Escobedo",
    "Guerrero",
    "Hidalgo",
    "Jiménez",
    "Juárez",
    "Progreso",
    "Candela",
    "Sierra Mojada",
  ],
  Colima: [
    "Colima",
    "Manzanillo",
    "Villa de Álvarez",
    "Tecomán",
    "Comala",
    "Armería",
    "Coquimatlán",
    "Cuauhtémoc",
    "Ixtlahuacán",
    "Minatitlán",
  ],
  Durango: [
    "Durango",
    "Gómez Palacio",
    "Lerdo",
    "Ciudad Lerdo",
    "Santiago Papasquiaro",
    "El Salto",
    "Guadalupe Victoria",
    "Vicente Guerrero",
    "Canatlán",
    "Nuevo Ideal",
    "San Juan del Río",
    "Tamazula",
    "Pueblo Nuevo",
    "Mezquital",
    "Cuencamé",
    "Peñón Blanco",
    "San Dimas",
    "Rodeo",
    "Guadalupe Victoria",
    "Suchil",
  ],
  "Estado de México": [
    "Toluca",
    "Naucalpan de Juárez",
    "Tlalnepantla de Baz",
    "Ecatepec de Morelos",
    "Huixquilucan",
    "Metepec",
    "Chimalhuacán",
    "Nezahualcóyotl",
    "Atizapán de Zaragoza",
    "Cuautitlán Izcalli",
    "Ixtapaluca",
    "Tecámac",
    "Chalco",
    "Valle de Chalco",
    "Los Reyes Acaquilpan",
    "Coacalco de Berriozábal",
    "Tultitlán",
    "Almoloya de Juárez",
    "Texcoco",
    "Zinacantepec",
  ],
  Guanajuato: [
    "León",
    "Guanajuato",
    "Irapuato",
    "Celaya",
    "Salamanca",
    "San Miguel de Allende",
    "Silao",
    "Dolores Hidalgo",
    "San Luis de la Paz",
    "Pénjamo",
    "San Francisco del Rincón",
    "Uriangato",
    "Valle de Santiago",
    "Moroleón",
    "Abasolo",
    "San José Iturbide",
    "Cortazar",
    "Apaseo el Grande",
    "Apaseo el Alto",
    "Comonfort",
  ],
  Guerrero: [
    "Acapulco",
    "Chilpancingo",
    "Iguala",
    "Chilapa",
    "Zihuatanejo",
    "Taxco",
    "Ometepec",
    "Tlapa",
    "Ciudad Altamirano",
    "Tecpan de Galeana",
    "Petatlán",
    "Cruz Grande",
    "Atoyac de Álvarez",
    "Coyuca de Benítez",
    "Zumpango del Río",
    "Huitzuco",
    "Teloloapan",
    "Arcelia",
    "San Marcos",
    "Tixtla",
  ],
  Hidalgo: [
    "Pachuca",
    "Tulancingo",
    "Tula",
    "Pachuca de Soto",
    "Mineral de la Reforma",
    "Tizayuca",
    "Ixmiquilpan",
    "Huejutla",
    "Actopan",
    "Sahagún",
    "Tepeji del Río",
    "Zimapán",
    "Apan",
    "Huichapan",
    "Tlahuelilpan",
    "Atotonilco de Tula",
    "Mixquiahuala",
    "Progreso",
    "Tezontepec",
    "Jacala",
  ],
  Jalisco: [
    "Guadalajara",
    "Zapopan",
    "Tlaquepaque",
    "Tonalá",
    "Puerto Vallarta",
    "Tlajomulco de Zúñiga",
    "Ciudad Guzmán",
    "Tepatitlán",
    "Ocotlán",
    "Arandas",
    "Lagos de Moreno",
    "Autlán",
    "Ameca",
    "Tala",
    "Zapotlanejo",
    "Tuxpan",
    "El Salto",
    "Jocotepec",
    "Chapala",
    "San Juan de los Lagos",
  ],
  "Michoacán de Ocampo": [
    "Morelia",
    "Uruapan",
    "Zamora",
    "Lázaro Cárdenas",
    "Sahuayo",
    "Pátzcuaro",
    "Apatzingán",
    "Ciudad Hidalgo",
    "Purépero",
    "Puruándiro",
    "La Piedad",
    "Zitácuaro",
    "Hidalgo",
    "Maravatío",
    "Jiquilpan",
    "Tacámbaro",
    "Quiroga",
    "Coalcomán",
    "Tepalcatepec",
    "Los Reyes",
  ],
  Morelos: [
    "Cuernavaca",
    "Jiutepec",
    "Cuautla",
    "Temixco",
    "Yautepec",
    "Jojutla",
    "Puente de Ixtla",
    "Zacatepec",
    "Tepoztlán",
    "Emiliano Zapata",
    "Ayala",
    "Xochitepec",
    "Tlaltizapán",
    "Atlatlahucan",
    "Tlayacapan",
    "Ocuituco",
    "Tetecala",
    "Amacuzac",
    "Coatlán del Río",
    "Mazatepec",
  ],
  Nayarit: [
    "Tepic",
    "Bahía de Banderas",
    "Xalisco",
    "Santiago Ixcuintla",
    "Compostela",
    "San Blas",
    "Acaponeta",
    "Tecuala",
    "Ixtlán del Río",
    "Ruiz",
    "Rosamorada",
    "Tuxpan",
    "Ahuacatlán",
    "Amatlán de Cañas",
    "Jala",
    "Del Nayar",
    "Santa María del Oro",
    "San Pedro Lagunillas",
    "La Yesca",
    "Huajicori",
  ],
  "Nuevo León": [
    "Monterrey",
    "San Pedro Garza García",
    "San Nicolás de los Garza",
    "Apodaca",
    "Santa Catarina",
    "Guadalupe",
    "San Jerónimo",
    "García",
    "Escobedo",
    "Santiago",
    "Salinas Victoria",
    "Ciénega de Flores",
    "Pesquería",
    "Marín",
    "Doctor Arroyo",
    "Mina",
    "Hualahuises",
    "General Terán",
    "Montemorelos",
    "Linares",
  ],
  Oaxaca: [
    "Oaxaca de Juárez",
    "Salina Cruz",
    "Juchitán",
    "Huatulco",
    "Puerto Escondido",
    "Tuxtepec",
    "San Juan Bautista Tuxtepec",
    "Miahuatlán",
    "Nochixtlán",
    "Huajuapan de León",
    "Pochutla",
    "Matías Romero",
    "Pinotepa Nacional",
    "Tlaxiaco",
    "Ixtlán",
    "Ejutla",
    "Ocotlán",
    "Zimatlán",
    "Tlacolula",
    "Putla",
  ],
  Puebla: [
    "Puebla",
    "Tehuacán",
    "Atlixco",
    "San Martín Texmelucan",
    "Amozoc",
    "Teziutlán",
    "San Pedro Cholula",
    "San Andrés Cholula",
    "Izúcar de Matamoros",
    "Tehuacán",
    "Cholula",
    "Huauchinango",
    "Xicotepec",
    "Libres",
    "Acatzingo",
    "Acatlán",
    "Zacatlán",
    "Chignahuapan",
    "Tecamachalco",
    "Puebla de Zaragoza",
  ],
  Querétaro: [
    "Querétaro",
    "San Juan del Río",
    "Corregidora",
    "El Marqués",
    "Tequisquiapan",
    "San Joaquín",
    "Jalpan",
    "Ezequiel Montes",
    "Cadereyta de Montes",
    "Amealco",
    "Pedro Escobedo",
    "Tolimán",
    "Pinal de Amoles",
    "Landa",
    "Arroyo Seco",
    "Colón",
    "Peñamiller",
    "Huimilpan",
    "Santa Rosa Jáuregui",
    "Villa Corregidora",
  ],
  "Quintana Roo": [
    "Cancún",
    "Playa del Carmen",
    "Chetumal",
    "Tulum",
    "Cozumel",
    "Isla Mujeres",
    "Bacalar",
    "Puerto Morelos",
    "Felipe Carrillo Puerto",
    "José María Morelos",
    "Lázaro Cárdenas",
    "Solidaridad",
    "Benito Juárez (QR)",
    "Othón P. Blanco",
    "Isla Mujeres",
    "Cozumel",
    "Bacalar",
    "Puerto Morelos",
    "Holbox",
  ],
  "San Luis Potosí": [
    "San Luis Potosí",
    "Soledad de Graciano Sánchez",
    "Ciudad Valles",
    "Matehuala",
    "Rioverde",
    "Tamazunchale",
    "Cerritos",
    "Villa de Reyes",
    "Xilitla",
    "Aquismón",
    "Ciudad Fernández",
    "Ébano",
    "Santa María del Río",
    "Villa de Ramos",
    "Tamuín",
    "Axtla de Terrazas",
    "Salinas",
    "Ciudad del Maíz",
    "Tamasopo",
    "Matlapa",
  ],
  Sinaloa: [
    "Culiacán",
    "Mazatlán",
    "Los Mochis",
    "Guasave",
    "Guamúchil",
    "Navolato",
    "Salvador Alvarado",
    "Ahome",
    "El Fuerte",
    "Choix",
    "Badiraguato",
    "Cosalá",
    "San Ignacio",
    "Mocorito",
    "Elota",
    "Concordia",
    "Rosario",
    "Escuinapa",
    "La Cruz",
    "Angostura",
  ],
  Sonora: [
    "Hermosillo",
    "Ciudad Obregón",
    "Nogales",
    "San Luis Río Colorado",
    "Navojoa",
    "Guaymas",
    "Cajeme",
    "Caborca",
    "Cananea",
    "Magdalena",
    "Agua Prieta",
    "San Carlos",
    "Puerto Peñasco",
    "Empalme",
    "Huatabampo",
    "Etchojoa",
    "Bácum",
    "Villa Juárez",
    "Baviácora",
    "Ures",
  ],
  Tabasco: [
    "Villahermosa",
    "Cárdenas",
    "Comalcalco",
    "Huimanguillo",
    "Cunduacán",
    "Centla",
    "Paraíso",
    "Jalpa de Méndez",
    "Nacajuca",
    "Macuspana",
    "Balancán",
    "Emiliano Zapata",
    "Jonuta",
    "Tenosique",
    "Tacotalpa",
    "Teapa",
    "Jalapa",
    "Centro",
    "Frontera",
    "Santa Rosalía",
  ],
  Tamaulipas: [
    "Ciudad Victoria",
    "Tampico",
    "Reynosa",
    "Matamoros",
    "Nuevo Laredo",
    "Ciudad Madero",
    "Altamira",
    "Río Bravo",
    "San Fernando",
    "Soto la Marina",
    "Tula",
    "González",
    "El Mante",
    "Valle Hermoso",
    "Xicoténcatl",
    "Jaumave",
    "Miguel Alemán",
    "Camargo",
    "Guerrero",
    "Bustamante",
  ],
  Tlaxcala: [
    "Tlaxcala",
    "Apizaco",
    "Huamantla",
    "Chiautempan",
    "Calpulalpan",
    "San Pablo del Monte",
    "Zacatelco",
    "Contla",
    "Santa Ana Chiautempan",
    "Teolocholco",
    "Nativitas",
    "Santa Cruz Tlaxcala",
    "Tepeyanco",
    "Acuamanala",
    "Tenancingo",
    "Ixtenco",
    "Tetlatlahuca",
    "Papalotla",
    "Xaloztoc",
    "Tocatlán",
  ],
  "Veracruz de Ignacio de la Llave": [
    "Veracruz",
    "Xalapa",
    "Coatzacoalcos",
    "Poza Rica",
    "Córdoba",
    "Orizaba",
    "Minatitlán",
    "Tuxpan",
    "San Andrés Tuxtla",
    "Martínez de la Torre",
    "Coatepec",
    "Papantla",
    "Acayucan",
    "Tierra Blanca",
    "Las Choapas",
    "Pánuco",
    "Río Blanco",
    "Perote",
    "Agua Dulce",
    "Ciudad Mendoza",
  ],
  Yucatán: [
    "Mérida",
    "Valladolid",
    "Tizimín",
    "Umán",
    "Kanasín",
    "Progreso",
    "Tekax",
    "Ticul",
    "Chemax",
    "Motul",
    "Hunucmá",
    "Oxkutzcab",
    "Izamal",
    "Peto",
    "Maxcanú",
    "Halachó",
    "Tixkokob",
    "Tecoh",
    "Espita",
    "Acanceh",
  ],
  Zacatecas: [
    "Zacatecas",
    "Fresnillo",
    "Guadalupe",
    "Jerez",
    "Río Grande",
    "Calera",
    "Sombrerete",
    "Ojocaliente",
    "Pinos",
    "Villanueva",
    "Nochistlán",
    "Tlaltenango",
    "Valparaíso",
    "Luis Moya",
    "Genaro Codina",
    "Cuauhtémoc",
    "Chalchihuites",
    "Trinidad García de la Cadena",
    "General Francisco R. Murguía",
    "General Pánfilo Natera",
  ],
};

// ============================================
// ESTRUCTURA: Ciudad → Municipios
// ============================================
export const MUNICIPIOS_POR_CIUDAD: Record<string, string[]> = {
  // Aguascalientes
  Aguascalientes: [
    "Aguascalientes",
    "Jesús María",
    "Pabellón de Arteaga",
    "San Francisco de los Romo",
    "Asientos",
  ],
  Calvillo: ["Calvillo", "Rincón de Romos", "Cosío", "Tepezalá", "El Llano"],

  // Baja California
  Tijuana: ["Tijuana", "Playas de Rosarito", "Tecate", "Ensenada", "Mexicali"],
  Mexicali: ["Mexicali", "Tecate", "Tijuana", "Ensenada", "San Quintín"],
  Ensenada: [
    "Ensenada",
    "Tijuana",
    "Playas de Rosarito",
    "Tecate",
    "San Quintín",
  ],

  // Baja California Sur
  "La Paz": ["La Paz", "Los Cabos", "Comondú", "Loreto", "Mulegé"],
  "Los Cabos": ["Los Cabos", "La Paz", "Comondú", "Loreto", "Mulegé"],
  Loreto: ["Loreto", "Comondú", "Mulegé", "La Paz", "Los Cabos"],

  // Campeche
  Campeche: ["Campeche", "Champotón", "Carmen", "Escárcega", "Calakmul"],
  "Ciudad del Carmen": [
    "Carmen",
    "Palizada",
    "Champotón",
    "Campeche",
    "Escárcega",
  ],

  // Ciudad de México
  "Ciudad de México": [
    "Álvaro Obregón",
    "Azcapotzalco",
    "Benito Juárez (CDMX)",
    "Coyoacán",
    "Cuajimalpa",
  ],

  // Chiapas
  "Tuxtla Gutiérrez": [
    "Tuxtla Gutiérrez",
    "Chiapa de Corzo",
    "Berriozábal",
    "Ocozocoautla",
    "Suchiapa",
  ],
  "San Cristóbal de las Casas": [
    "San Cristóbal",
    "Teopisca",
    "Chamula",
    "Zinacantán",
    "Amatenango",
  ],
  Tapachula: [
    "Tapachula",
    "Cacahoatán",
    "Unión Juárez",
    "Huehuetán",
    "Mazatán",
  ],

  // Chihuahua
  Chihuahua: [
    "Chihuahua",
    "Aquiles Serdán",
    "Santa Isabel",
    "San Francisco de Conchos",
    "Saucillo",
  ],
  "Ciudad Juárez": [
    "Juárez",
    "Guadalupe",
    "Praxedis G. Guerrero",
    "Ascensión",
    "Janos",
  ],

  // Coahuila de Zaragoza
  Saltillo: ["Saltillo", "Arteaga", "Ramos Arizpe", "General Cepeda", "Parras"],
  Torreón: [
    "Torreón",
    "Matamoros",
    "San Pedro",
    "Viesca",
    "Francisco I. Madero",
  ],
  Monclova: ["Monclova", "Frontera", "Castaños", "Nadadores", "Abasolo"],
  "Piedras Negras": [
    "Piedras Negras",
    "Nava",
    "Allende",
    "Morelos",
    "Zaragoza",
  ],
  "Ciudad Acuña": ["Acuña", "Jiménez", "Progreso", "Escobedo", "Candela"],

  // Colima
  Colima: ["Colima", "Villa de Álvarez", "Comala", "Cuauhtémoc", "Coquimatlán"],
  Manzanillo: [
    "Manzanillo",
    "Armería",
    "Tecomán",
    "Colima",
    "Villa de Álvarez",
  ],
  Tecomán: ["Tecomán", "Armería", "Manzanillo", "Colima", "Ixtlahuacán"],

  // Durango
  Durango: [
    "Durango",
    "Canatlán",
    "Nuevo Ideal",
    "San Juan del Río",
    "Mezquital",
  ],
  "Gómez Palacio": [
    "Gómez Palacio",
    "Lerdo",
    "Mapimí",
    "Tlahualilo",
    "San Luis del Cordero",
  ],
  Lerdo: [
    "Lerdo",
    "Gómez Palacio",
    "Mapimí",
    "Tlahualilo",
    "San Juan de Guadalupe",
  ],
  "Santiago Papasquiaro": [
    "Santiago Papasquiaro",
    "Tamazula",
    "San Dimas",
    "Otáez",
    "Canelas",
  ],
  "El Salto": [
    "El Salto",
    "Pueblo Nuevo",
    "Guadalupe Victoria",
    "San Bernardino",
    "Suchil",
  ],

  // Estado de México
  Toluca: ["Toluca", "Metepec", "Lerma", "Zinacantepec", "Almoloya de Juárez"],
  "Naucalpan de Juárez": [
    "Naucalpan",
    "Tlalnepantla",
    "Atizapán",
    "Huixquilucan",
    "Cuautitlán Izcalli",
  ],
  "Tlalnepantla de Baz": [
    "Tlalnepantla",
    "Naucalpan",
    "Atizapán",
    "Ecatepec",
    "Coacalco",
  ],
  "Ecatepec de Morelos": [
    "Ecatepec",
    "Nezahualcóyotl",
    "Chimalhuacán",
    "Coacalco",
    "Tecámac",
  ],
  Huixquilucan: [
    "Huixquilucan",
    "Naucalpan",
    "Atizapán",
    "Tlalnepantla",
    "Lerma",
  ],

  // Guanajuato
  León: ["León", "Silao", "San Francisco del Rincón", "Purísima", "Romita"],
  Guanajuato: ["Guanajuato", "Silao", "Irapuato", "León", "Dolores Hidalgo"],
  Irapuato: ["Irapuato", "Silao", "León", "Salamanca", "Pénjamo"],
  Celaya: [
    "Celaya",
    "Comonfort",
    "Apaseo el Grande",
    "Apaseo el Alto",
    "Tarimoro",
  ],
  Salamanca: ["Salamanca", "Irapuato", "Celaya", "Pénjamo", "Abasolo"],

  // Guerrero
  Acapulco: [
    "Acapulco",
    "Coyuca de Benítez",
    "San Marcos",
    "Tecpan",
    "Petatlán",
  ],
  Chilpancingo: [
    "Chilpancingo",
    "Chilapa",
    "Tixtla",
    "Quechultenango",
    "Zumpango",
  ],
  Iguala: ["Iguala", "Taxco", "Cocula", "Tepecoacuilco", "Huitzuco"],
  Chilapa: ["Chilapa", "Chilpancingo", "Tlapa", "Ahuacuotzingo", "Zitlala"],
  Zihuatanejo: [
    "Zihuatanejo",
    "Lázaro Cárdenas",
    "Petatlán",
    "Tecpan",
    "Coyuca de Catalán",
  ],

  // Hidalgo
  Pachuca: [
    "Pachuca",
    "Mineral de la Reforma",
    "San Agustín Tlaxiaca",
    "Zapotlán",
    "Mineral del Monte",
  ],
  Tulancingo: [
    "Tulancingo",
    "Cuautepec",
    "Santiago Tulantepec",
    "Singuilucan",
    "Acaxochitlán",
  ],
  Tula: [
    "Tula",
    "Atotonilco de Tula",
    "Tepeji del Río",
    "Tlaxcoapan",
    "Tezontepec",
  ],
  "Pachuca de Soto": [
    "Pachuca",
    "Mineral de la Reforma",
    "San Agustín Tlaxiaca",
    "Zapotlán",
    "Mineral del Chico",
  ],
  Tizayuca: [
    "Tizayuca",
    "Tolcayuca",
    "Villa de Tezontepec",
    "Atitalaquia",
    "Ajacuba",
  ],

  // Jalisco
  Guadalajara: ["Guadalajara", "Zapopan", "Tlaquepaque", "Tonalá", "El Salto"],
  Zapopan: ["Zapopan", "Guadalajara", "Tlaquepaque", "Tonalá", "Tlajomulco"],
  Tlaquepaque: ["Tlaquepaque", "Guadalajara", "Zapopan", "Tonalá", "El Salto"],
  Tonalá: ["Tonalá", "Guadalajara", "Zapopan", "Tlaquepaque", "El Salto"],
  "Puerto Vallarta (Jalisco)": [
    "Puerto Vallarta",
    "Cabo Corrientes",
    "Tomatlán",
    "Talpa",
    "Mascota",
  ],

  // Michoacán
  Morelia: ["Morelia", "Tarímbaro", "Charo", "Álvaro Obregón", "Queréndaro"],
  Uruapan: [
    "Uruapan",
    "Tingambato",
    "Ziracuaretiro",
    "Nuevo Parangaricutiro",
    "Peribán",
  ],
  Zamora: ["Zamora", "Jacona", "Briseñas", "Villamar", "Chavinda"],
  "Lázaro Cárdenas": [
    "Lázaro Cárdenas",
    "Coalcomán",
    "Aquila",
    "Tumbiscatío",
    "Arteaga",
  ],
  Sahuayo: [
    "Sahuayo",
    "Jiquilpan",
    "Venustiano Carranza",
    "Cojumatlán",
    "Briseñas",
  ],

  // Morelos
  Cuernavaca: [
    "Cuernavaca",
    "Jiutepec",
    "Temixco",
    "Emiliano Zapata",
    "Huitzilac",
  ],
  Jiutepec: [
    "Jiutepec",
    "Cuernavaca",
    "Temixco",
    "Emiliano Zapata",
    "Yautepec",
  ],
  Cuautla: ["Cuautla", "Yautepec", "Ayala", "Tlaltizapán", "Tepoztlán"],
  Temixco: [
    "Temixco",
    "Cuernavaca",
    "Jiutepec",
    "Emiliano Zapata",
    "Mazatepec",
  ],
  Yautepec: ["Yautepec", "Cuautla", "Ayala", "Tlaltizapán", "Tepoztlán"],

  // Nayarit
  Tepic: ["Tepic", "Xalisco", "San Blas", "Compostela", "Bahía de Banderas"],
  "Bahía de Banderas": [
    "Bahía de Banderas",
    "Compostela",
    "Tepic",
    "San Blas",
    "Xalisco",
  ],
  Xalisco: ["Xalisco", "Tepic", "San Blas", "Compostela", "Ixtlán del Río"],
  "Santiago Ixcuintla": [
    "Santiago Ixcuintla",
    "Tecuala",
    "Acaponeta",
    "Ruiz",
    "Rosamorada",
  ],
  Compostela: [
    "Compostela",
    "Bahía de Banderas",
    "Tepic",
    "San Blas",
    "Xalisco",
  ],

  // Nuevo León
  Monterrey: ["Monterrey", "San Pedro", "San Nicolás", "Guadalupe", "Apodaca"],
  "San Pedro Garza García": [
    "San Pedro",
    "Monterrey",
    "Santa Catarina",
    "García",
    "San Nicolás",
  ],
  "San Nicolás de los Garza": [
    "San Nicolás",
    "Monterrey",
    "Guadalupe",
    "Apodaca",
    "San Pedro",
  ],
  Apodaca: ["Apodaca", "Monterrey", "San Nicolás", "Guadalupe", "Pesquería"],
  "Santa Catarina": [
    "Santa Catarina",
    "San Pedro",
    "García",
    "Monterrey",
    "Santiago",
  ],

  // Oaxaca
  "Oaxaca de Juárez": [
    "Oaxaca",
    "Santa Cruz Xoxocotlán",
    "San Andrés Huayápam",
    "San Agustín de las Juntas",
    "Tlalixtac",
  ],
  "Salina Cruz": [
    "Salina Cruz",
    "Tehuantepec",
    "Juchitán",
    "San Mateo del Mar",
    "Santa María Mixtequilla",
  ],
  Juchitán: [
    "Juchitán",
    "Tehuantepec",
    "Salina Cruz",
    "Unión Hidalgo",
    "Ixtepec",
  ],
  Huatulco: [
    "Santa María Huatulco",
    "San Pedro Pochutla",
    "Candelaria Loxicha",
    "Pluma Hidalgo",
    "San Miguel del Puerto",
  ],
  "Puerto Escondido": [
    "San Pedro Mixtepec",
    "Santa María Colotepec",
    "San Mateo Piñas",
    "San Gabriel Mixtepec",
    "Santiago Jamiltepec",
  ],

  // Puebla
  Puebla: [
    "Puebla",
    "San Andrés Cholula",
    "San Pedro Cholula",
    "Cuautlancingo",
    "Amozoc",
  ],
  Tehuacán: [
    "Tehuacán",
    "Ajalpan",
    "Teotitlán",
    "Tepanco",
    "Santiago Miahuatlán",
  ],
  Atlixco: [
    "Atlixco",
    "Tochimilco",
    "Huaquechula",
    "Santa Isabel Cholula",
    "San Diego la Mesa",
  ],
  "San Martín Texmelucan": [
    "San Martín Texmelucan",
    "San Matías Tlalancaleca",
    "Santa Clara Ocoyucan",
    "Amozoc",
    "Puebla",
  ],
  Amozoc: [
    "Amozoc",
    "Puebla",
    "Cuautlancingo",
    "San Pedro Cholula",
    "San Andrés Cholula",
  ],

  // Querétaro
  Querétaro: [
    "Querétaro",
    "Corregidora",
    "El Marqués",
    "San Juan del Río",
    "Santa Rosa Jáuregui",
  ],
  "San Juan del Río": [
    "San Juan del Río",
    "Tequisquiapan",
    "Ezequiel Montes",
    "Cadereyta",
    "Amealco",
  ],
  Corregidora: [
    "Corregidora",
    "Querétaro",
    "El Marqués",
    "San Juan del Río",
    "Pedro Escobedo",
  ],
  "El Marqués": [
    "El Marqués",
    "Querétaro",
    "Corregidora",
    "San Juan del Río",
    "Amealco",
  ],
  Tequisquiapan: [
    "Tequisquiapan",
    "San Juan del Río",
    "Ezequiel Montes",
    "Cadereyta",
    "Amealco",
  ],

  // Quintana Roo
  Cancún: [
    "Benito Juárez (QR)",
    "Isla Mujeres",
    "Puerto Morelos",
    "Solidaridad",
    "Cozumel",
  ],
  "Playa del Carmen": [
    "Solidaridad",
    "Tulum",
    "Cozumel",
    "Lázaro Cárdenas",
    "Benito Juárez (Playa del Carmen)",
  ],
  Chetumal: [
    "Othón P. Blanco",
    "Bacalar",
    "José María Morelos",
    "Felipe Carrillo Puerto",
    "Lázaro Cárdenas",
  ],
  Tulum: [
    "Tulum",
    "Solidaridad",
    "Felipe Carrillo Puerto",
    "José María Morelos",
    "Bacalar",
  ],
  Cozumel: [
    "Cozumel",
    "Solidaridad",
    "Benito Juárez (Cozumel)",
    "Isla Mujeres",
    "Puerto Morelos",
  ],

  // San Luis Potosí
  "San Luis Potosí": [
    "San Luis Potosí",
    "Soledad de Graciano Sánchez",
    "Cerro de San Pedro",
    "Mexquitic",
    "Villa de Reyes",
  ],
  "Soledad de Graciano Sánchez": [
    "Soledad",
    "San Luis Potosí",
    "Cerro de San Pedro",
    "Mexquitic",
    "Villa de Reyes",
  ],
  "Ciudad Valles": [
    "Ciudad Valles",
    "Tamuín",
    "Ebano",
    "El Naranjo",
    "San Vicente",
  ],
  Matehuala: [
    "Matehuala",
    "Villa de Guadalupe",
    "Real de Catorce",
    "Villa de la Paz",
    "Charcas",
  ],
  Rioverde: [
    "Rioverde",
    "Ciudad Fernández",
    "San Ciro",
    "Alaquines",
    "Santa María del Río",
  ],

  // Sinaloa
  Culiacán: ["Culiacán", "Navolato", "Badiraguato", "Cosalá", "Mocorito"],
  Mazatlán: ["Mazatlán", "Concordia", "Rosario", "San Ignacio", "Culiacán"],
  "Los Mochis": ["Ahome", "El Fuerte", "Choix", "Guasave", "Angostura"],
  Guasave: ["Guasave", "Ahome", "Angostura", "El Fuerte", "Badiraguato"],
  Guamúchil: [
    "Salvador Alvarado",
    "Guasave",
    "Angostura",
    "Mocorito",
    "Culiacán",
  ],

  // Sonora
  Hermosillo: ["Hermosillo", "Cajeme", "Guaymas", "Navojoa", "Caborca"],
  "Ciudad Obregón": ["Cajeme", "Navojoa", "Huatabampo", "Etchojoa", "Bácum"],
  Nogales: ["Nogales", "Santa Cruz", "Cananea", "Naco", "Agua Prieta"],
  "San Luis Río Colorado": [
    "San Luis Río Colorado",
    "Mexicali",
    "Puerto Peñasco",
    "Plutarco Elías Calles",
    "General Luna",
  ],
  Navojoa: ["Navojoa", "Cajeme", "Huatabampo", "Etchojoa", "Bácum"],

  // Tabasco
  Villahermosa: ["Centro", "Nacajuca", "Jalpa", "Cunduacán", "Comalcalco"],
  Cárdenas: ["Cárdenas", "Huimanguillo", "Comalcalco", "Paraíso", "Jalpa"],
  Comalcalco: ["Comalcalco", "Cárdenas", "Paraíso", "Huimanguillo", "Centro"],
  Huimanguillo: [
    "Huimanguillo",
    "Cárdenas",
    "Comalcalco",
    "Macuspana",
    "Jalpa",
  ],
  Cunduacán: ["Cunduacán", "Centro", "Comalcalco", "Cárdenas", "Jalpa"],

  // Tamaulipas
  "Ciudad Victoria": ["Victoria", "Llera", "Güémez", "Padilla", "Hidalgo"],
  Tampico: ["Tampico", "Ciudad Madero", "Altamira", "Pánuco", "González"],
  Reynosa: [
    "Reynosa",
    "Río Bravo",
    "Valle Hermoso",
    "Matamoros",
    "San Fernando",
  ],
  Matamoros: [
    "Matamoros",
    "Reynosa",
    "Valle Hermoso",
    "San Fernando",
    "Soto la Marina",
  ],
  "Nuevo Laredo": [
    "Nuevo Laredo",
    "Anáhuac",
    "Guerrero",
    "Mier",
    "Miguel Alemán",
  ],

  // Tlaxcala
  Tlaxcala: [
    "Tlaxcala",
    "Chiautempan",
    "Apetatitlán",
    "Santa Ana",
    "Teolocholco",
  ],
  Apizaco: ["Apizaco", "Tzompantepec", "Xaloztoc", "Cuaxomulco", "Teacalco"],
  Huamantla: ["Huamantla", "Ixtenco", "Terrenate", "Cuapiaxtla", "Zitlaltépec"],
  Chiautempan: [
    "Chiautempan",
    "Tlaxcala",
    "Apetatitlán",
    "Santa Ana",
    "Teolocholco",
  ],
  Calpulalpan: [
    "Calpulalpan",
    "El Carmen",
    "Cuapiaxtla",
    "Altzayanca",
    "Tlaxco",
  ],

  // Veracruz
  Veracruz: [
    "Veracruz",
    "Boca del Río",
    "Medellín",
    "Alvarado",
    "Manlio Fabio Altamirano",
  ],
  Xalapa: [
    "Xalapa",
    "Banderilla",
    "Coatepec",
    "Emiliano Zapata",
    "Rafael Lucio",
  ],
  Coatzacoalcos: [
    "Coatzacoalcos",
    "Minatitlán",
    "Acayucan",
    "Las Choapas",
    "Agua Dulce",
  ],
  "Poza Rica": ["Poza Rica", "Papantla", "Coatzintla", "Tihuatlán", "Cazones"],
  Córdoba: ["Córdoba", "Orizaba", "Fortín", "Amatlán", "Ixtaczoquitlán"],

  // Yucatán
  Mérida: ["Mérida", "Umán", "Kanasín", "Conkal", "Progreso"],
  Valladolid: ["Valladolid", "Tizimín", "Espita", "Temozón", "Chemax"],
  Tizimín: ["Tizimín", "Valladolid", "Espita", "Sucilá", "Panabá"],
  Umán: ["Umán", "Mérida", "Kanasín", "Conkal", "Hunucmá"],
  Kanasín: ["Kanasín", "Mérida", "Umán", "Acanceh", "Tecoh"],

  // Zacatecas
  Zacatecas: ["Zacatecas", "Guadalupe", "Morelos", "Vetagrande", "Calera"],
  Fresnillo: ["Fresnillo", "Valparaíso", "Sain Alto", "Río Grande", "Jerez"],
  Guadalupe: ["Guadalupe", "Zacatecas", "Morelos", "Vetagrande", "Calera"],
  Jerez: ["Jerez", "Fresnillo", "Susticacán", "Tepetongo", "Río Grande"],
  "Río Grande": [
    "Río Grande",
    "Fresnillo",
    "Sain Alto",
    "Cañitas",
    "Juan Aldama",
  ],
};

// ============================================
// ESTRUCTURA: Municipio → Colonias
// ============================================
export const COLONIAS_POR_MUNICIPIO: Record<string, string[]> = {
  // CDMX
  Cuauhtémoc: [
    "Roma Norte",
    "Roma Sur",
    "Condesa",
    "Juárez",
    "Centro",
    "Tabacalera",
    "Doctores",
    "Obrera",
    "San Rafael",
    "Santa María la Ribera",
  ],
  "Miguel Hidalgo": [
    "Polanco",
    "Lomas de Chapultepec",
    "Anzures",
    "Pensil",
    "Escandón",
    "Tacubaya",
    "Observatorio",
    "San Miguel Chapultepec",
    "Argentina Poniente",
    "Granada",
  ],
  Coyoacán: [
    "Coyoacán Centro",
    "Del Carmen",
    "Pedregal de Santo Domingo",
    "Santa Úrsula Coapa",
    "Pueblo de los Reyes",
    "San Diego Churubusco",
    "Santa Catarina",
    "San Mateo",
    "San Lucas",
    "San Francisco Culhuacán",
  ],
  "Álvaro Obregón": [
    "Santa Fe",
    "Tlacopac",
    "Pueblo de San Bartolo Ameyalco",
    "Pueblo de Santa Lucia",
    "Pueblo de San Mateo Tlaltenango",
    "Pueblo de San Pedro Cuajimalpa",
    "Pueblo de Santa Rosa Xochiac",
    "Pueblo de San Lorenzo Acopilco",
    "Pueblo de San Jerónimo Lídice",
    "Pueblo de San Angel",
  ],
  Azcapotzalco: [
    "Centro de Azcapotzalco",
    "San Álvaro",
    "Santa Inés",
    "San Marcos",
    "San Sebastián",
    "Santa María Malinalco",
    "San Juan Tlilhuaca",
    "San Andrés de las Salinas",
    "San Antonio",
    "Reynosa Tamaulipas",
  ],
  "Benito Juárez (CDMX)": [
    "Del Valle",
    "Narvarte",
    "Nápoles",
    "Portales",
    "Mixcoac",
    "Ciudad de los Deportes",
    "Insurgentes Mixcoac",
    "San Pedro de los Pinos",
    "Alamos",
    "Nativitas",
  ],
  "Gustavo A. Madero": [
    "Linda Vista",
    "Tepeyac Insurgentes",
    "Industrial",
    "Vallejo",
    "San Pedro el Chico",
    "Villa Gustavo A. Madero",
    "Martín Carrera",
    "Cuautepec",
    "La Pastora",
    "San Juan de Aragón",
  ],
  Iztacalco: [
    "Iztacalco Centro",
    "La Cruz",
    "Agua Caliente",
    "Miguel de la Madrid Hurtado",
    "El Rodeo",
    "Granjas México",
    "Zapotla",
    "Santa Anita",
    "La Asunción",
    "San Pedro Iztacalco",
  ],
  Iztapalapa: [
    "Iztapalapa Centro",
    "Santa Martha Acatitla",
    "San Lorenzo Tezonco",
    "San Juan Xalpa",
    "El Manto",
    "Desarrollo Urbano Quetzalcoatl",
    "Lomas de Estrella",
    "San Miguel Teotongo",
    "Guadalupe del Moral",
    "Santa María Aztahuacán",
  ],
  Tlalpan: [
    "Jardines de la Montaña",
    "Bosques de Tlalpan",
    "Bosque del Pedregal",
    "Pedregal de San Ángel",
    "Centro de Tlalpan",
    "Toriello Guerra",
    "San Lorenzo Huipulco",
    "Barrio La Fama",
    "Isidro Fabela",
    "Parque del Pedregal",
  ],
  Xochimilco: [
    "San Lorenzo Atemoaya",
    "San Gregorio Atlapulco",
    "San Francisco Tlalnepantla",
    "San Andrés Ahuayucan",
    "San Lucas Xochimanca",
    "San Luis Tlaxialtemalco",
    "San Mateo Xalpa",
    "Santa María Tepepan",
    "Santa Cecilia Tepetlapa",
    "Santa Cruz Acalpixca",
  ],
  "La Magdalena Contreras": [
    "La Magdalena Contreras Centro",
    "San Jerónimo Lídice",
    "San Bernabé Ocotepec",
    "San Nicolás Totolapan",
    "San Bartolo Ameyalco",
    "El Tanque",
    "Las Cruces",
    "El Rosal",
    "San Francisco",
    "El Ermitaño",
  ],
  "Venustiano Carranza": [
    "Venustiano Carranza Centro",
    "Moctezuma",
    "Pensador Mexicano",
    "Jamaica",
    "Morelos",
    "Santa Cruz",
    "Ampliación Penitenciaria",
    "Romero Rubio",
    "Simón Bolívar",
    "10 de Mayo",
  ],
  Tláhuac: [
    "Tláhuac Centro",
    "San Juan Ixtayopan",
    "San Nicolás Tetelco",
    "San Andrés Mixquic",
    "San Francisco Tlaltenco",
    "Santiago Zapotitlán",
    "Santa Catarina Yecahuizotl",
    "San Juan Ixhuatepec",
    "San Miguel",
    "La Estación",
  ],
  "Milpa Alta": [
    "Milpa Alta Centro",
    "San Antonio Tecómitl",
    "San Bartolomé Xicomulco",
    "San Francisco Tecoxpa",
    "San Ildefonso",
    "San Juan Tepenahuac",
    "San Lorenzo Tlacoyucan",
    "San Pablo Oztotepec",
    "San Pedro Atocpan",
    "San Salvador Cuauhtenco",
  ],
  "Cuajimalpa de Morelos": [
    "Cuajimalpa de Morelos Centro",
    "San Mateo Tlaltenango",
    "San Lorenzo Acopilco",
    "San Pedro Cuajimalpa",
    "Santa Rosa Xochiac",
    "San Pablo Chimalpa",
    "San Luis de las Peras",
    "Contadero",
    "Abdías García Soto",
    "Agua Bendita",
  ],

  // Nuevo León
  Monterrey: [
    "Centro",
    "Tecnológico",
    "Cumbres",
    "San Jerónimo",
    "Mitras",
    "San Agustín",
    "Valle Poniente",
    "Valle Oriente",
    "Del Paseo",
    "Loma Larga",
  ],
  "San Pedro Garza García": [
    "Del Valle",
    "Fuentes del Valle",
    "Valle de San Ángel",
    "Valle Oriente",
    "Calzada del Valle",
    "Tampiquito",
    "Lomas del Valle",
    "San Ángel",
    "Del Carmen",
    "Tizapan",
  ],
  Guadalupe: [
    "Contry",
    "Linda Vista",
    "Guadalupe Centro",
    "San Rafael",
    "Las Escobas",
    "Valle de Santa Lucía",
    "Jardines de la Moderna",
    "Valle Soleado",
    "Colonial",
    "Villas de Guadalupe",
  ],
  Apodaca: [
    "Ciudad Apodaca",
    "Ex Hacienda Santa Rosa",
    "Paseo de San Miguel",
    "Villas de Alcalá",
    "Hacienda Las Bugambilias",
    "Real de San Agustín",
    "Villa de San Miguel",
    "Hacienda San Miguel",
    "Privadas de Santa Rosa",
    "Ex Hacienda San Francisco",
    "Huinalá",
    "Pueblo Nuevo",
    "Las Palmas",
  ],
  "San Nicolás de los Garza": [
    "Anáhuac",
    "Las Puentes",
    "Residencial Roble",
    "San Nicolás Centro",
    "Hidalgo",
    "Nuevo Repueblo",
    "Las Cumbres",
    "Monterreal",
    "Praderas",
    "Valles de San Nicolás",
    "Cuauhtémoc",
  ],

  // Jalisco
  Guadalajara: [
    "Centro Histórico",
    "Americana",
    "Providencia",
    "Ladrón de Guevara",
    "Monraz",
    "Arcos Vallarta",
    "Chapultepec",
    "Lomas del Valle",
    "Moderna",
    "El Fresno",
  ],
  Zapopan: [
    "Puerta de Hierro",
    "Ciudad del Sol",
    "Valle Real",
    "Andares",
    "La Gran Plaza",
    "Patria",
    "Prados Tepeyac",
    "Jardines del Valle",
    "Tabachines",
    "La Estancia",
  ],
  Tlaquepaque: [
    "Tlaquepaque Centro",
    "El Álamo",
    "Lomas del Cuatro",
    "San Martín de las Flores",
    "San Pedrito",
    "Santa María Tequepexpan",
    "Tateposco",
    "Las Juntas",
    "El Tapatío",
    "San Francisco",
  ],
  Tonalá: [
    "Tonalá Centro",
    "Paseos del Sol",
    "Lomas de la Soledad",
    "Colinas de la Normal",
    "El Rosario",
    "San Gaspar",
    "Coyula",
    "Jardines de Tonalá",
    "Paseos del Prado",
    "El Zalate",
  ],
  "Puerto Vallarta (Jalisco)": [
    "Centro",
    "Marina Vallarta",
    "Zona Romántica",
    "Conchas Chinas",
    "Hotel Zone",
    "Versalles",
    "Fluvial Vallarta",
    "Las Glorias",
    "Amapas",
    "Alta Vista",
  ],

  // Querétaro
  Querétaro: [
    "Juriquilla",
    "Centro",
    "Milenio III",
    "Carretas",
    "San Pablo",
    "El Campanario",
    "Altos del Marqués",
    "Cimatario",
    "Jardines de Querétaro",
    "San Isidro",
  ],
  Corregidora: [
    "El Pueblito",
    "Candiles",
    "Balvanera",
    "San José",
    "Los Olvera",
    "Tequisquiapan",
    "San Rafael",
    "Santa Bárbara",
    "El Cerrito",
    "Jardines de la Corregidora",
  ],

  // Puebla
  Puebla: [
    "Centro Histórico",
    "Angelópolis",
    "La Paz",
    "Humboldt",
    "Chulavista",
    "San Manuel",
    "El Mirador",
    "Las Ánimas",
    "La Noria",
    "San Baltazar",
  ],
  "San Andrés Cholula": [
    "Lomas de Angelópolis",
    "San Andrés Centro",
    "Cholula de Rivadavia",
    "San Bernardino Tlaxcalancingo",
    "San Antonio Cacalotepec",
    "San Luis Tehuiloyocan",
    "San Francisco Acatepec",
    "Santa María Tonantzintla",
    "San Rafael Comac",
    "San Juan Tlautla",
  ],

  // Quintana Roo
  Solidaridad: [
    "Quinta Avenida",
    "Playacar",
    "Gonzalo Guerrero",
    "Colosio",
    "Ejidal",
    "Luis Donaldo Colosio",
    "Nicolas Bravo",
    "Forjadores",
    "Villas del Sol",
    "Santa Fe",
  ],
  "Benito Juárez (QR)": [
    "Zona Hotelera",
    "Puerto Cancún",
    "SM 15",
    "SM 20",
    "SM 31",
    "Del Valle",
    "Narvarte",
    "Nápoles",
    "Portales",
    "Mixcoac",
    "Zona Hotelera",
    "Puerto Cancún",
    "SM 15",
    "SM 20",
    "SM 31",
  ],
  Tulum: [
    "Aldea Zama",
    "La Veleta",
    "Centro",
    "Zama Garden",
    "Region 15",
    "Region 8",
    "Boca Paila",
    "Tankah",
    "Akumal",
    "Chemuyil",
  ],
  Cozumel: [
    "Centro",
    "San Miguel",
    "Corpus Christi",
    "Flamingos",
    "Las Palmas",
    "San Gervasio",
    "El Cedral",
    "La Gloria",
    "San Juan",
    "Santa Rosa",
  ],

  // Veracruz
  Veracruz: [
    "Reforma",
    "Centro",
    "Fraccionamiento Virginia",
    "Mocambo",
    "Costa de Oro",
    "Boca del Río",
    "Las Amapolas",
    "Río Medio",
    "Mandinga",
    "Antón Lizardo",
  ],
  "Boca del Río": [
    "Costa de Oro",
    "El Morro",
    "Mocambo",
    "Playa de Oro",
    "Jardines",
    "Las Américas",
    "Villas Tiburón",
    "Boca del Río Centro",
    "Veracruz",
    "Las Palmas",
  ],

  // Yucatán
  Mérida: [
    "Centro",
    "Montejo",
    "Altabrisa",
    "Cholul",
    "Itzimná",
    "Benito Juárez (Mérida)",
    "San Ramón",
    "Dzitya",
    "San Antonio Cinta",
    "Las Américas",
  ],
  "Puerto Vallarta": [
    "Centro",
    "Marina Vallarta",
    "Zona Romántica",
    "Conchas Chinas",
    "Amapas",
  ],

  // Nuevo León
  "Santa Catarina": [
    "La Fama",
    "Lomas de Santa Catarina",
    "Valle de las Mitras",
    "Santa Catarina Centro",
    "Fátima",
  ],

  // Estado de México
  "Naucalpan de Juárez": [
    "Satelite",
    "Lomas Verdes",
    "Echegaray",
    "Tecamachalco",
    "San Bartolo",
  ],
  "Tlalnepantla de Baz": [
    "Valle Dorado",
    "Viveros del Valle",
    "Tlalnepantla Centro",
    "San Lucas",
    "San Javier",
  ],
  "Ecatepec de Morelos": [
    "Jardines de Morelos",
    "Las Américas",
    "Ciudad Azteca",
    "Venta de Carpio",
    "Nueva Aragón",
  ],
  Huixquilucan: [
    "Interlomas",
    "Bosque Real",
    "La Herradura",
    "Jesus del Monte",
    "Palmas",
  ],

  // Quintana Roo

  // Baja California
  Ensenada: [
    "Zona Centro",
    "Valle de Guadalupe",
    "El Sauzal",
    "San Antonio de las Minas",
    "El Tigre",
  ],
  "Playas de Rosarito": [
    "Rosarito Centro",
    "Cantamar",
    "Puerto Nuevo",
    "Popotla",
    "Santa Anita",
  ],
};

// ============================================
// HELPERS
// ============================================
export const getCiudadesPorEstado = (estado: string): string[] => {
  return CIUDADES_POR_ESTADO[estado] || [];
};

export const getMunicipiosPorCiudad = (ciudad: string): string[] => {
  return MUNICIPIOS_POR_CIUDAD[ciudad] || [];
};

export const getColoniasPorMunicipio = (municipio: string): string[] => {
  return COLONIAS_POR_MUNICIPIO[municipio] || [];
};
