export const COLONIAS_POR_MUNICIPIO: Record<string, string[]> = {
  // CDMX
  Cuauhtémoc: [
    "Roma Norte",
    "Roma Sur",
    "Condesa",
    "Juárez",
    "Centro",
    "Tabacalera",
    "Doctores",
    "Obrera",
    "San Rafael",
    "Santa María la Ribera",
  ],
  "Miguel Hidalgo": [
    "Polanco",
    "Lomas de Chapultepec",
    "Anzures",
    "Pensil",
    "Escandón",
    "Tacubaya",
    "Observatorio",
    "San Miguel Chapultepec",
    "Argentina Poniente",
    "Granada",
  ],
  Coyoacán: [
    "Coyoacán Centro",
    "Del Carmen",
    "Pedregal de Santo Domingo",
    "Santa Úrsula Coapa",
    "Pueblo de los Reyes",
    "San Diego Churubusco",
    "Santa Catarina",
    "San Mateo",
    "San Lucas",
    "San Francisco Culhuacán",
  ],
  "Álvaro Obregón": [
    "Santa Fe",
    "Tlacopac",
    "Pueblo de San Bartolo Ameyalco",
    "Pueblo de Santa Lucia",
    "Pueblo de San Mateo Tlaltenango",
    "Pueblo de San Pedro Cuajimalpa",
    "Pueblo de Santa Rosa Xochiac",
    "Pueblo de San Lorenzo Acopilco",
    "Pueblo de San Jerónimo Lídice",
    "Pueblo de San Angel",
  ],
  Azcapotzalco: [
    "Centro de Azcapotzalco",
    "San Álvaro",
    "Santa Inés",
    "San Marcos",
    "San Sebastián",
    "Santa María Malinalco",
    "San Juan Tlilhuaca",
    "San Andrés de las Salinas",
    "San Antonio",
    "Reynosa Tamaulipas",
  ],
  "Benito Juárez (CDMX)": [
    "Del Valle",
    "Narvarte",
    "Nápoles",
    "Portales",
    "Mixcoac",
    "Ciudad de los Deportes",
    "Insurgentes Mixcoac",
    "San Pedro de los Pinos",
    "Alamos",
    "Nativitas",
  ],
  "Gustavo A. Madero": [
    "Linda Vista",
    "Tepeyac Insurgentes",
    "Industrial",
    "Vallejo",
    "San Pedro el Chico",
    "Villa Gustavo A. Madero",
    "Martín Carrera",
    "Cuautepec",
    "La Pastora",
    "San Juan de Aragón",
  ],
  Iztacalco: [
    "Iztacalco Centro",
    "La Cruz",
    "Agua Caliente",
    "Miguel de la Madrid Hurtado",
    "El Rodeo",
    "Granjas México",
    "Zapotla",
    "Santa Anita",
    "La Asunción",
    "San Pedro Iztacalco",
  ],
  Iztapalapa: [
    "Iztapalapa Centro",
    "Santa Martha Acatitla",
    "San Lorenzo Tezonco",
    "San Juan Xalpa",
    "El Manto",
    "Desarrollo Urbano Quetzalcoatl",
    "Lomas de Estrella",
    "San Miguel Teotongo",
    "Guadalupe del Moral",
    "Santa María Aztahuacán",
  ],
  Tlalpan: [
    "Jardines de la Montaña",
    "Bosques de Tlalpan",
    "Bosque del Pedregal",
    "Pedregal de San Ángel",
    "Centro de Tlalpan",
    "Toriello Guerra",
    "San Lorenzo Huipulco",
    "Barrio La Fama",
    "Isidro Fabela",
    "Parque del Pedregal",
  ],
  Xochimilco: [
    "San Lorenzo Atemoaya",
    "San Gregorio Atlapulco",
    "San Francisco Tlalnepantla",
    "San Andrés Ahuayucan",
    "San Lucas Xochimanca",
    "San Luis Tlaxialtemalco",
    "San Mateo Xalpa",
    "Santa María Tepepan",
    "Santa Cecilia Tepetlapa",
    "Santa Cruz Acalpixca",
  ],
  "La Magdalena Contreras": [
    "La Magdalena Contreras Centro",
    "San Jerónimo Lídice",
    "San Bernabé Ocotepec",
    "San Nicolás Totolapan",
    "San Bartolo Ameyalco",
    "El Tanque",
    "Las Cruces",
    "El Rosal",
    "San Francisco",
    "El Ermitaño",
  ],
  "Venustiano Carranza": [
    "Venustiano Carranza Centro",
    "Moctezuma",
    "Pensador Mexicano",
    "Jamaica",
    "Morelos",
    "Santa Cruz",
    "Ampliación Penitenciaria",
    "Romero Rubio",
    "Simón Bolívar",
    "10 de Mayo",
  ],
  Tláhuac: [
    "Tláhuac Centro",
    "San Juan Ixtayopan",
    "San Nicolás Tetelco",
    "San Andrés Mixquic",
    "San Francisco Tlaltenco",
    "Santiago Zapotitlán",
    "Santa Catarina Yecahuizotl",
    "San Juan Ixhuatepec",
    "San Miguel",
    "La Estación",
  ],
  "Milpa Alta": [
    "Milpa Alta Centro",
    "San Antonio Tecómitl",
    "San Bartolomé Xicomulco",
    "San Francisco Tecoxpa",
    "San Ildefonso",
    "San Juan Tepenahuac",
    "San Lorenzo Tlacoyucan",
    "San Pablo Oztotepec",
    "San Pedro Atocpan",
    "San Salvador Cuauhtenco",
  ],
  "Cuajimalpa de Morelos": [
    "Cuajimalpa de Morelos Centro",
    "San Mateo Tlaltenango",
    "San Lorenzo Acopilco",
    "San Pedro Cuajimalpa",
    "Santa Rosa Xochiac",
    "San Pablo Chimalpa",
    "San Luis de las Peras",
    "Contadero",
    "Abdías García Soto",
    "Agua Bendita",
  ],

  // Nuevo León
  Monterrey: [
    "Centro",
    "Tecnológico",
    "Cumbres",
    "San Jerónimo",
    "Mitras",
    "San Agustín",
    "Valle Poniente",
    "Valle Oriente",
    "Del Paseo",
    "Loma Larga",
  ],
  "San Pedro Garza García": [
    "Del Valle",
    "Fuentes del Valle",
    "Valle de San Ángel",
    "Valle Oriente",
    "Calzada del Valle",
    "Tampiquito",
    "Lomas del Valle",
    "San Ángel",
    "Del Carmen",
    "Tizapan",
  ],
  Guadalupe: [
    "Contry",
    "Linda Vista",
    "Guadalupe Centro",
    "San Rafael",
    "Las Escobas",
    "Valle de Santa Lucía",
    "Jardines de la Moderna",
    "Valle Soleado",
    "Colonial",
    "Villas de Guadalupe",
  ],
  Apodaca: [
    "Ciudad Apodaca",
    "Ex Hacienda Santa Rosa",
    "Paseo de San Miguel",
    "Villas de Alcalá",
    "Hacienda Las Bugambilias",
    "Real de San Agustín",
    "Villa de San Miguel",
    "Hacienda San Miguel",
    "Privadas de Santa Rosa",
    "Ex Hacienda San Francisco",
    "Huinalá",
    "Pueblo Nuevo",
    "Las Palmas",
  ],
  "San Nicolás de los Garza": [
    "Anáhuac",
    "Las Puentes",
    "Residencial Roble",
    "San Nicolás Centro",
    "Hidalgo",
    "Nuevo Repueblo",
    "Las Cumbres",
    "Monterreal",
    "Praderas",
    "Valles de San Nicolás",
    "Cuauhtémoc",
  ],

  // Jalisco
  Guadalajara: [
    "Centro Histórico",
    "Americana",
    "Providencia",
    "Ladrón de Guevara",
    "Monraz",
    "Arcos Vallarta",
    "Chapultepec",
    "Lomas del Valle",
    "Moderna",
    "El Fresno",
  ],
  Zapopan: [
    "Puerta de Hierro",
    "Ciudad del Sol",
    "Valle Real",
    "Andares",
    "La Gran Plaza",
    "Patria",
    "Prados Tepeyac",
    "Jardines del Valle",
    "Tabachines",
    "La Estancia",
  ],
  Tlaquepaque: [
    "Tlaquepaque Centro",
    "El Álamo",
    "Lomas del Cuatro",
    "San Martín de las Flores",
    "San Pedrito",
    "Santa María Tequepexpan",
    "Tateposco",
    "Las Juntas",
    "El Tapatío",
    "San Francisco",
  ],
  Tonalá: [
    "Tonalá Centro",
    "Paseos del Sol",
    "Lomas de la Soledad",
    "Colinas de la Normal",
    "El Rosario",
    "San Gaspar",
    "Coyula",
    "Jardines de Tonalá",
    "Paseos del Prado",
    "El Zalate",
  ],
  "Puerto Vallarta (Jalisco)": [
    "Centro",
    "Marina Vallarta",
    "Zona Romántica",
    "Conchas Chinas",
    "Hotel Zone",
    "Versalles",
    "Fluvial Vallarta",
    "Las Glorias",
    "Amapas",
    "Alta Vista",
  ],

  // Querétaro
  Querétaro: [
    "Juriquilla",
    "Centro",
    "Milenio III",
    "Carretas",
    "San Pablo",
    "El Campanario",
    "Altos del Marqués",
    "Cimatario",
    "Jardines de Querétaro",
    "San Isidro",
  ],
  Corregidora: [
    "El Pueblito",
    "Candiles",
    "Balvanera",
    "San José",
    "Los Olvera",
    "Tequisquiapan",
    "San Rafael",
    "Santa Bárbara",
    "El Cerrito",
    "Jardines de la Corregidora",
  ],

  // Puebla
  Puebla: [
    "Centro Histórico",
    "Angelópolis",
    "La Paz",
    "Humboldt",
    "Chulavista",
    "San Manuel",
    "El Mirador",
    "Las Ánimas",
    "La Noria",
    "San Baltazar",
  ],
  "San Andrés Cholula": [
    "Lomas de Angelópolis",
    "San Andrés Centro",
    "Cholula de Rivadavia",
    "San Bernardino Tlaxcalancingo",
    "San Antonio Cacalotepec",
    "San Luis Tehuiloyocan",
    "San Francisco Acatepec",
    "Santa María Tonantzintla",
    "San Rafael Comac",
    "San Juan Tlautla",
  ],

  // Quintana Roo
  Solidaridad: [
    "Quinta Avenida",
    "Playacar",
    "Gonzalo Guerrero",
    "Colosio",
    "Ejidal",
    "Luis Donaldo Colosio",
    "Nicolas Bravo",
    "Forjadores",
    "Villas del Sol",
    "Santa Fe",
  ],
  "Benito Juárez (QR)": [
    "Zona Hotelera",
    "Puerto Cancún",
    "SM 15",
    "SM 20",
    "SM 31",
    "Del Valle",
    "Narvarte",
    "Nápoles",
    "Portales",
    "Mixcoac",
    "Zona Hotelera",
    "Puerto Cancún",
    "SM 15",
    "SM 20",
    "SM 31",
  ],
  Tulum: [
    "Aldea Zama",
    "La Veleta",
    "Centro",
    "Zama Garden",
    "Region 15",
    "Region 8",
    "Boca Paila",
    "Tankah",
    "Akumal",
    "Chemuyil",
  ],
  Cozumel: [
    "Centro",
    "San Miguel",
    "Corpus Christi",
    "Flamingos",
    "Las Palmas",
    "San Gervasio",
    "El Cedral",
    "La Gloria",
    "San Juan",
    "Santa Rosa",
  ],

  // Veracruz
  Veracruz: [
    "Reforma",
    "Centro",
    "Fraccionamiento Virginia",
    "Mocambo",
    "Costa de Oro",
    "Boca del Río",
    "Las Amapolas",
    "Río Medio",
    "Mandinga",
    "Antón Lizardo",
  ],
  "Boca del Río": [
    "Costa de Oro",
    "El Morro",
    "Mocambo",
    "Playa de Oro",
    "Jardines",
    "Las Américas",
    "Villas Tiburón",
    "Boca del Río Centro",
    "Veracruz",
    "Las Palmas",
  ],

  // Yucatán
  Mérida: [
    "Centro",
    "Montejo",
    "Altabrisa",
    "Cholul",
    "Itzimná",
    "Benito Juárez (Mérida)",
    "San Ramón",
    "Dzitya",
    "San Antonio Cinta",
    "Las Américas",
  ],
  "Puerto Vallarta": [
    "Centro",
    "Marina Vallarta",
    "Zona Romántica",
    "Conchas Chinas",
    "Amapas",
  ],

  // Nuevo León
  "Santa Catarina": [
    "La Fama",
    "Lomas de Santa Catarina",
    "Valle de las Mitras",
    "Santa Catarina Centro",
    "Fátima",
  ],

  // Estado de México
  "Naucalpan de Juárez": [
    "Satelite",
    "Lomas Verdes",
    "Echegaray",
    "Tecamachalco",
    "San Bartolo",
  ],
  "Tlalnepantla de Baz": [
    "Valle Dorado",
    "Viveros del Valle",
    "Tlalnepantla Centro",
    "San Lucas",
    "San Javier",
  ],
  "Ecatepec de Morelos": [
    "Jardines de Morelos",
    "Las Américas",
    "Ciudad Azteca",
    "Venta de Carpio",
    "Nueva Aragón",
  ],
  Huixquilucan: [
    "Interlomas",
    "Bosque Real",
    "La Herradura",
    "Jesus del Monte",
    "Palmas",
  ],

  // Quintana Roo

  // Baja California
  Ensenada: [
    "Zona Centro",
    "Valle de Guadalupe",
    "El Sauzal",
    "San Antonio de las Minas",
    "El Tigre",
  ],
  "Playas de Rosarito": [
    "Rosarito Centro",
    "Cantamar",
    "Puerto Nuevo",
    "Popotla",
    "Santa Anita",
  ],
};
